version: '3'

services:
  mariadb:
    build: requirements/mariadb/.
    image: mariadb:inception
    container_name: my-mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - my-network
    restart: on-failure
    env_file:
      - .env


  nginx:
    build: requirements/nginx/.
    image: nginx:inception
    container_name: my-nginx
    depends_on:
      - wordpress
    ports:
      - '443:443'
    networks:
      - my-network
    volumes:
      - wordpress_data:/var/www/html
    restart: on-failure
    env_file:
      - .env


  wordpress:
    build: requirements/wordpress/.
    image: wordpress:inception
    container_name: my-wordpress
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    networks:
      - my-network
    volumes:
      - wordpress_data:/var/www/html
    restart: on-failure
    env_file:
      - .env
  
networks:
  my-network:

volumes:
  mariadb_data:
  wordpress_data:
