version: '3'

services:
  mariadb:
    build: mariadb/.
    image: mariadb:inception
    ports:
      - 3306:3306
    volumes:
      - ./data:/home
    environment:
      - DB_NAME=MyDataBase
      - DB_USER=DataBaseUser
      - DB_PASS=1234


